config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'
    resources :posts, only:[:new, :show, :create] do
      resource :bookmarks, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
    end
    resources :users, only:[:index, :show]
    resources :categories, only:[:show, :index]
  end

  namespace :admin do
    resources :users, only:[:index, :show]
    resources :posts, only:[:show, :destroy]
    resources :categories, only:[:index, :create, :destroy]
  end

  devise_for :user, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :user_name, presence: true, uniqueness: true, length: {minimum: 3}
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(6)
    @get_favorite = Favorite.where(post_id: @posts.ids)
  end

end

app/views/admin/users/index.html.erb
<div class=".container">
  <% @users.each do |user| %>
  <div class="row justify-content-center mt-3 mx-3 alert alert-secondary">
    <div class="mr-3">
      <h4>ユーザーネーム</h4>
    </div>
    <div class="mr-3">
      <h4>
        <%= link_to admin_user_path(user.id) do %>
          <%= user.user_name %>
        <% end %>
      </h4>
    </div>
    <div class="mr-3">
      <h4>最終ログイン</h4>
    </div>
    <div class="mr-3">
      <h4>
        <%= l user.last_sign_in_at, format: :short %>
      </h4>
    </div>
    <div class="mr-3">
      <h4>投稿数</h4>
    </div>
    <div class="mr-3">
      <h4>
        <%= user.posts.count %>
      </h4>
    </div>
    <div class="mr-3">
      <h4>アカウント作成日時</h4>
    </div>
    <div class="mr-3">
      <h4>
        <%= l user.created_at, format: :short %>
      </h4>
    </div>
  </div>
  <% end %>
  <div class="row fixed-bottom">
    <div class="mx-auto mb-3 pagination pagination-lg">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class=".container">
  <div class="row mt-5 ml-5">
    <div class="mr-5">
      <h1><%= @user.user_name %>さん の詳細ページ</h1>
    </div>
    <div class="mr-5 d-flex align-items-end">
      <h3>
        投稿数 <%= @user.posts.count %>
      </h3>
    </div>
    <div class="mr-5 d-flex align-items-end">
      <h3>
        いいね <%= @get_favorite.count %>
      </h3>
    </div>
  </div>
  <div class="row mt-5 justify-content-center">
  <% @posts.each do |post| %>
    <div class="card col-3 mx-5 mt-3 flex-wrap shadow-lg" style="width: 18rem;">
      <div class="card-body">
        <h3 class="card-title text-secondary"><%= post.post_title %></h3>
        <p class="card-text text-secondary lead"><%= post.post_text.truncate(10) %>...</p>
         <%= link_to "もっと見る",  admin_post_path(post.id), class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
  </div>
  <div class="row fixed-bottom">
    <div class="mx-auto mb-3 pagination pagination-lg">
      <%= paginate @posts %>
    </div>
  </div>
</div>