config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'
    resources :posts, only:[:new, :show, :create] do
      resource :bookmarks, only:[:create, :destroy]
      resource :favorites, only:[:create, :destroy]
    end
    resources :users, only:[:index, :show]
    resources :categories, only:[:show, :index]
  end

  namespace :admin do
    resources :users, only:[:index, :show]
    resources :posts, only:[:show, :destroy]
    resources :categories, only:[:index, :create, :destroy]
  end

  devise_for :user, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'layouts/errors', model: f.object %>

app/views/layouts/_serach.html.erb
<div>
  <%= form_with url: search_path, local: true, method: :get do |f| %>
  <div class="d-inline-flex">
    <%= f.text_field :keyword, value: @keyword, placeholder: "検索ワード", class: "search" %>
  </div>
  <div class="d-inline-flex">
    <%= f.submit "検索", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIFEPass</title>
    <%= csrf_meta_tags %>

    <script src="https://kit.fontawesome.com/59339ca57a.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class=".container">
      <nav class="navbar navbar-expand-md navbar-secondary fixed-top bg-dark">
      <div class="navbar-brand">
        <%= link_to root_path do %>
          <h1 class="text-white">
            LIFE Pass
          </h1>
        <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto" >
          <div class="nav-link ml-3">
            <h2 class="text-white">
              Hello!! <%= current_user.user_name %> さん
            </h2>
          </div>
          <div class="nav-link ml-3">
            <%= link_to new_post_path do %>
              <h4 class="text-white">
                投稿する
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-3">
            <%= link_to users_path(current_user.id) do %>
              <h4 class="text-white">
                マイページ
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-3">
            <%= link_to categories_path do %>
              <h4 class="text-white">
                カテゴリ一覧
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-3">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <h4 class="text-white">
                ログアウト
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-5">
            <%= render 'layouts/serach' %>
          </div>
        </ul>
      </div>
      <% elsif admin_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <div class="nav-link ml-3">
            <%= link_to admin_categories_path do %>
              <h4 class="text-white">
                カテゴリ一覧
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-3">
            <%= link_to admin_users_path do %>
              <h4 class="text-white">
                会員一覧
              </h4>
            <% end %>
          </div>
          <div class="nav-link ml-3">
            <%= link_to destroy_admin_session_path, method: :delete do %>
              <h4 class="text-white">
                ログアウト
              </h4>
            <% end %>
          </div>
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <div class="nav-link">
            <%= link_to about_path do %>
              <h4 class="text-white">
                LIFE Passって？
              </h4>
            <% end %>
          </div>
          <div class="nav-link">
            <%= link_to new_user_session_path do %>
              <h4 class="text-white">
                ログイン
              </h4>
            <% end %>
          </div>
          <div class="nav-link">
            <%= link_to new_user_registration_path do %>
              <h4 class="text-white">
                サインアップ
              </h4>
            <% end %>
          </div>
        </ul>
      </div>
      <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>